Dev hbh
naive-react/naive pull request #4
Opened 2023-07-24 01:07 UTC by huangbh1024

2023-07-24 03:10 UTC, srqAndwr requested changes

2023-07-24 03:10 UTC, srqAndwr commented on src/internal/close/index.tsx
> +export const NBaseClose = (props: PropsWithChildren<NBaseCloseProps>) => {
children 没用到就删了吧

2023-07-24 03:10 UTC, srqAndwr commented on src/internal/close/index.tsx
> +        'n-base-close--absolute': absolute,
absolute 是没实现嘛，还是要交给外部去控制，外部控制好像更好一点儿。

2023-08-09 01:03 UTC, huangbh1024 commented on src/internal/close/index.tsx
> +export const NBaseClose = (props: PropsWithChildren<NBaseCloseProps>) => {
已删除

2023-08-09 01:03 UTC, huangbh1024 commented on src/internal/close/index.tsx
> +        'n-base-close--absolute': absolute,
![image](https://github.com/naive-react/naive/assets/72372968/854d8bae-9d41-4079-a437-0b2b81d1655b)
props，有用到

2023-08-09 02:04 UTC, srqAndwr approved these changes

2023-08-09 02:04 UTC, merged